# Generated by Django 5.0.6 on 2024-10-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankName', models.CharField(max_length=25)),
                ('Branch', models.CharField(max_length=25)),
                ('cardno', models.CharField(max_length=25)),
                ('cardholder', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
