# Generated by Django 5.0.6 on 2024-10-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adddptr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='assigndoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Contact', models.BigIntegerField()),
                ('Email', models.CharField(max_length=25)),
                ('Symptoms', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=100)),
                ('Doctor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(max_length=25)),
                ('Pwd', models.CharField(max_length=15)),
                ('Utype', models.CharField(max_length=20)),
            ],
        ),
    ]
