# Generated by Django 5.0.4 on 2024-10-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medoffapp', '0002_eprescripotion_shedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shedule',
            name='bill',
        ),
        migrations.AddField(
            model_name='eprescripotion',
            name='bill',
            field=models.IntegerField(null=True),
        ),
    ]
